source-file ~/.tmux.conf

# Create a session for all magmutual dev
new-session -s magmutualdev -n andysandbox -d
set main-pane-height 95%
run-shell "sleep 1"

# Create an environment for AndySandbox
send-keys -t magmutualdev:1 'cd ~/andysandbox' C-m
send-keys -t magmutualdev:1 'nvim' C-m
send-keys -t magmutualdev:1 ',sf' 

# Split AndySandbox into a main-horizontal split
run-shell "sleep 1"
split-window -v -t magmutualdev:1
select-layout -t magmutualdev:1 main-horizontal
send-keys -t magmutualdev:1.2 'cd ~/andysandbox' C-m

# Create an environment for DevSandbox
run-shell "sleep 1"
new-window -n devsandbox -t magmutualdev
send-keys -t magmutualdev:2 'cd ~/magmutual' C-m

# Switch to the first window and create a main-horizontal split
run-shell "sleep 1"
select-window -t magmutualdev:1
run-shell "sleep 1"
send-keys -t magmutualdev:1 'tmux select-layout -t magmutualdev:1 main-horizontal' C-m

# Create a window environment for root of dotfiles
new-session -s dotfiles -n root -d
send-keys -t dotfiles:1 'cd ~/dotfiles' C-m
send-keys -t dotfiles:1 'nvim' C-m
send-keys -t dotfiles:1 ',sf' 

# Create a window environment for root of neovim
run-shell 'sleep 1'
# # Enter neovim directly and open file search in telescope
new-window -n neovim -t dotfiles 
send-keys -t dotfiles:2 'cd ~/dotfiles/nvim' C-m
send-keys -t dotfiles:2 'nvim' C-m
send-keys -t dotfiles:2 ',sf' 

# Create a window environment for root of tmux
# # Enter neovim directly and open EV
run-shell "sleep 1"
new-window -n tmux -t dotfiles
send-keys -t dotfiles:3 'cd ~/dotfiles/tmux' C-m
send-keys -t dotfiles:3 'nvim' C-m
send-keys -t dotfiles:3 ',pv' 

# Switch back to magmutualdev
run-shell "sleep 1"
send-keys -t magmutualdev:1 'tmux switch-client -t magmutualdev' C-m
send-keys -t magmutualdev:1 'tmux select-layout -t magmutualdev:1 main-horizontal' C-m
