source-file ~/.tmux.conf

# Create a session for dotfiles
new-session -s dotfiles -n root -d
set main-pane-height 95%
run-shell "sleep 1"

# Create a window environment for root of dotfiles
send-keys -t dotfiles:1 'cd ~/dotfiles' C-m
send-keys -t dotfiles:1 'nvim' C-m

# Create a window environment for root of neovim
run-shell 'sleep 1'
# # Enter neovim directly and open file search in telescope
new-window -n neovim -t dotfiles 
send-keys -t dotfiles:2 'cd ~/dotfiles/nvim' C-m
send-keys -t dotfiles:2 'nvim' C-m
send-keys -t dotfiles:2 ',sf' 

# Create a window environment for root of tmux
# # Enter neovim directly and open EV
run-shell "sleep 1"
new-window -n tmux -t dotfiles
send-keys -t dotfiles:3 'cd ~/dotfiles/tmux' C-m

# Switch to second window( neovim )
run-shell "sleep 1"
select-window -t dotfiles:2
